---
abstract: 'Make your object constructors blow up on unknown attributes '
author:
  - 'Fuji, Goro (gfx) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MouseX::StrictConstructor
name: MouseX-StrictConstructor
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mouse: 0.62
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-MouseX-StrictConstructor.git
version: 0.01
